server.port=8081
server.address=127.0.0.1
logging.file.name=/srv/logs/systemstatus/systemstatus-api.log
cluster.nodes=${CLUSTER_NODES:}
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/homelab
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}